### ISSUE TITLE
minimap2 shows matches but none drawn

### ISSUE THREAD

**Issue by keiranmraine** [bcgsc/xmatchview#8] opened 2020-10-22 08:07 UTC
Hi,

I'm having some trouble getting the image to show links between a rearranged chromosome and the original reference.  The minimap2 output shows lots of contacts between the contigs I'm comparing and the program appears to run to completion, however the items below may be informative to you.

Please note that as using python3, Pillow was used instead of PIL.

## Program exits with non-zero exit code

The scrip completes ending as:

```
Saving xmv-HiC_1_scaffold_joined_1.fa_vs_chr6.fa.paf_m30_b500_r50_c500.png...
done.
```

But gives an exit code of `1`.

## No contacts in the image

Not sure if the program output is indicating repeats or the contact points here:

```
Drawing repeats...
HiC_1_scaffold_joined_1 (0-72) hits chr6  ::  mismatch 4.24 target(30)  block 72 target (500) 
HiC_1_scaffold_joined_1 (73-132) hits chr6  ::  mismatch 5.21 target(30)  block -58 target (500) 
...
HiC_1_scaffold_joined_1 (136409-137712) hits chr6  ::  mismatch 4.60 target(30)  block 1311 target (500) 
Saving xmv-HiC_1_scaffold_joined_1.fa_vs_chr6.fa.paf_m30_b500_r50_c500.png...
done.
# END OF OUTPUT
```

The resulting image has no links:

![xmv-HiC_1_scaffold_joined_1 fa_vs_chr6 fa paf_m30_b500_r50_c500](https://user-images.githubusercontent.com/3740323/96842876-81eca280-1445-11eb-9bc9-ae6d52f00a24.png)

Here's an example line from the minimap2 paf file:

```
HiC_1_scaffold_joined_1	68856307	52475424	57317502	+	chr6	170805979	116047608	120887336	4596641	4844553	60	tp:A:P	cm:i:835066	s1:i:4595480	s2:i:3444	dv:f:0.0011	rl:i:6735398
```

**Comment by warrenlr** [comment] 2020-10-22 14:39
that is strange indeed. There are user-defined parameters that control which links to plot, namely the minimum block (-b) length and the sequence identity cutoff (mismatch threshold -m between target/query colinear blocks). 

What is puzzling here is that colinear blocks do show on your draft, but not on the reference, and you should see a histogram of sequence identity ontop when colinear blocks appear on the reference.

The good news is that features get plotted, which makes me think the paf parser isn't recognizing the "chr6" entry in it, or that it is different from the header in the supplied reference FASTA (-s).  Are these files formatted in unix and did you use the exact same FASTA files for your minimap run?  I wonder if an improperly formatted FASTA (non-unix new line) may be causing the issue. 

Here's what I suggest you do:
1. Run the demo, does it plot the links? and does the image conforms to the corresponding image in the test folder? (this is to convince us that py3 with pillow works as well as the original)    
2. Share the command(s) you ran.  Also, Did you run the steps separately or using supplied bash scripts? If former, please include all commands you ran.  Also, xmv expects exact formatting, so if the steps were executed separately and there was a change in a name, even a space or different new line character, a sequence may not be recognized when parsing the alignment file.  
3. If 1) and 2) do not resolve the issue, we are happy to plot it for you & figure out what may be happening -- you'd just have to share your draft assembly section and the reference (is it human chr 6?)  

Cheers,
Rene

**Comment by keiranmraine** [comment] 2020-10-22 15:00
Thanks for getting back to me.

1. I ran the demo, and other than minor differences in fonts the output is the same.
2. I used the scripts you provided, but with a minor modification so that the gff files and font directory weren't required (wasn't clear if fonts were still needed with PIL/Pillow).

```diff
<    xmatchview.py -x $1_vs_$2.paf -q $1 -s $2 -a $3 -m $4 -b $5 -r $6 -c $7 -f png -y $8 -e $9 -p ${11}
---
>    xmatchview.py -x $1_vs_$2.paf -q $1 -s $2 -a $3 -m $4 -b $5 -r $6 -c $7 -f png
```

Command used, my parameters could be way off, but the example commands took way too long to run, so I gleaned values from the [xmatchview image](https://github.com/warrenlr/xmatchview/blob/master/xmv.png) in the README :

```
xmatchview_v1.2.3/runCompareTwoGenomesColinear.sh HiC_1_scaffold_joined_1.fa chr6.fa 200 30 500 50 500 . . minimap2 .
```

Is there any assumption that an `*.fai` file exists?

It takes a very long time to run this, so I'll liase with the person who owns the data to see if we can trim this down to a much smaller target/query for testing purposes.  I suspect they won't be happy sharing the whole construct.

**Comment by warrenlr** [comment] 2020-10-22 15:46
Good idea; 

I suspect it takes a long time to run because of the computation needed to build the histogram, which could be sped up by increasing the window size. Another culprit could be the dataset size. As you suggested, concentrate on a shorter region first, one you know is common between chr6 and your target— this will be faster to run and easier to troubleshoot. 

Since the demo works, I’m convinced that a formatting inconsistency exists in one of your fasta files.  Make sure you don’t have extra new line characters and when you generate a subset for your test run, make sure the headers do not contain characters other than a-z0-9.

**Comment by lcoombe** [comment] 2020-10-22 19:00
Hi @keiranmraine,

Another test you could do to ensure your installation/dependent libraries are working properly:
From the 'test' directory of the repo
```
../runCompareTwoGenomesColinear.sh FTL1_pa.fa FTL1_ss.fa 200 90 10 2 2 FTL1_pa.gff FTL1_ss.gff minimap2 /home/rwarren/fonts/truetype
```
(Just replacing the command with the path to the fonts on your system)

You should get an image that looks like this:
![xmv-FTL1_pa fa_vs_FTL1_ss fa paf_m90_b10_r2_c2](https://user-images.githubusercontent.com/11697335/96917433-c08e5700-145d-11eb-85cc-6fceb6eca552.png)

If that works for you fine, as Rene mentioned, it is most likely that the issue is a formatting issue with one of your input fasta files.

**Comment by keiranmraine** [comment] 2020-10-23 10:11
Hi @lcoombe I've already generated one of the test images, they render correctly with the exception of the fonts (pillow doesn't appear to have pif fonts included).  Would you mind confirming what `echo $?` give if executed directly after the test?  I've raised MR #9 which shows the example you provided (which gives exact replica of your image) gives an exit code of 1.

WRT the data I am using, the fasta files all conform to the standards expected by samtools and others.  I've generated an image both with the target seq defined as `chr6:13000000-17000000` and simply `target`(in both cases the query labeled as `query`).

Reducing the target to a 4MB chunk has identified the problem to be in the X-scaling.  If you look at the X-coord of the target in the image it steps in 50b.p. despite the reference being many Mb.p.  Note the right-hand Y-axis is absent. The links between query and target are there, but are almost completely horizontal in the earlier image.  You will note that I have set the scale to 1:500bp so even if the image width doesn't auto scale I'd expect ~1.2 Mb.p. in that axis (2400px image width).  This image was created before the docker image was generated with the official fonts:

![xmv-query fa_vs_target fa paf_m30_b500_r50_c500](https://user-images.githubusercontent.com/3740323/96991212-06135880-1520-11eb-8697-db8219862e50.png)

I'll work on reducing the data further while still retaining the problem (it still takes ~2h to run) so I can share it with you.

FYI, the inclusion of fonts in this repo is not as clear as it could be as the info is in a code block on a very long line.

**Comment by keiranmraine** [comment] 2020-10-23 13:01
I've now done 2 runs (using the docker image) and these suggest that the X-axis scale needs to be set so that the target can fit within a specific pixel width

Target of 1Mbp with 1:500 pixel is fine:
![1Mbp-xmv-query fa_vs_target fa paf_m99_b500_r50_c500](https://user-images.githubusercontent.com/3740323/97006572-f9026380-1537-11eb-87cb-08c145b32ab6.png)

Target of 4Mbs with 1:500 clearly doesn't fit:
![4Mbp-xmv-query fa_vs_target fa paf_m99_b500_r50_c500](https://user-images.githubusercontent.com/3740323/97006618-091a4300-1538-11eb-8fd3-2f1af9ca9304.png)

What is the maximum width of the plot area excluding boarders/padding?

It would be nice if an error was raised very early to indicate the image will be truncated.

**Comment by keiranmraine** [comment] 2020-10-23 13:50
Sorry, found another issue.  Using a 4Mbp target but scaling at 1:2000 keeps all the target visible, however the query doesn't appear to scale, so if it is over 1Mbp you get (I forgot to change the mm rate so exceptionally noisy):

![xmv-query fa_vs_target fa paf_m99_b500_r250_c2000](https://user-images.githubusercontent.com/3740323/97011382-80eb6c00-153e-11eb-81c6-869e2195b597.png).

It seems that it would be preferable to add an option for the scale to be auto calculated independently using the ref/alt lengths.  The option could be retained by using `0` as the request for auto scaling.

**Comment by warrenlr** [comment] 2020-10-23 14:25
thank you for the suggestions and feature requests @keiranmraine, we will definitely take into consideration.

Since the specific issue you originally reported is resolved, we will close it. But feel free to keep commenting here if you'd like.

Cheers,
Rene

**Closed by warrenlr** 2020-10-23 14:25 UTC
Labels: enhancement, help wanted, question

**Comment by warrenlr** [comment] 2020-10-23 15:20
In your above example, how large is the query sequence?

As for speeding things up, again, exploring the leap parameter would help. At the resolution of the image, where 1 pixel = 4000 bp, it would make sense to increase the leap to at least that order of magnitude (1,000 or even 10,000) without losing any information on the plot.

**Comment by keiranmraine** [comment] 2020-10-23 16:49
In that example the query is bigger than the target by a considerable margin, ~61Mbp vs 4Mbp, so that is back-to-front on what you would normally expect.

Yes, when running on the larger scale I changed the parameters to:

```
runCompareTwoGenomesColinear.sh query.fa target.fa 200 99 500 250 2000 . . minimap2 .
```

(using the modifications to the script detailed in #9 for optional values)

Adding guidance to the examples for appropriate settings as the scale value grows would be helpful.

**Comment by warrenlr** [comment] 2020-10-23 18:11
I've added error handling for the scaling v1.2.4

auto-scale would be more involved, because cmv support multi-fasta and the scaling is done at run time, as sequences are being read in memory.

In v1.2.4, xmv won't plot when one of the genomic feature extends beyond the plot width. 
The message includes a minimum scaling value to use to fit the features, which should be helpful and guide the user in selecting a value. 

As a general rule of thumb, scaling can be calculated as : feature length (bp) / plot width.  The width is set as 2400 px in xmatchview.    

A suggestion: In your example, because your query is so much larger than your reference, maybe you could flip them around?  ie. use the reference as your query, it may show better (esp. with the histogram).

**Comment by keiranmraine** [comment] 2020-10-26 13:28
FYI, the scaling doesn't take into account the boarders so despite the message indicating the image has been scaled to under 2400px width the image is still truncated (missing the right hand axis):

```
chr6 length = 170805979 bp, scaled to 2340 pixels
Total length = 170805979 bp, scaled to : 2340 pixels 
```

<img width="1236" alt="Screen Shot 2020-10-26 at 13 26 43" src="https://user-images.githubusercontent.com/3740323/97178160-049b9780-178f-11eb-9676-ca54583130a8.png">

**Comment by warrenlr** [comment] 2020-10-26 16:21
thanks for the feedback.  I made a fix, tested on a small example & committed. Could you please re-clone and try on your example?

**Comment by keiranmraine** [comment] 2020-10-26 18:19
I can confirm that this now recommends the appropriate scale level.
